version: '3'

volumes:
    influxdb_volume:
    grafana_volume:

services:

  mosquitto:
    build: mosquitto
    restart: unless-stopped
    ports:
       - "1883:1883"
       - "9001:9001"

  node-lox-mqtt-gw:
    build: node-lox-mqtt-gateway
    restart: unless-stopped

  influxdb:
      image: influxdb:1.8
      restart: unless-stopped
      ports:
        - "8083:8083"
        - "8086:8086"
        - "25826:25826/udp"
      volumes:
        - /data/docker_volumes/loxone_monitoring/influxdb:/var/lib/influxdb

  grafana:
      image: grafana/grafana-oss
      user: "0:0"
      restart: unless-stopped
      ports:
        - "3000:3000"
      volumes:
        - /data/docker_volumes/loxone_monitoring/grafana:/var/lib/grafana

  loxone2influx:
    build: loxone2influx
    restart: unless-stopped
    environment:
      - MQTT_ADDRESS=tcp://mosquitto:1883
      - LOXONE_MQTT_TOPIC_NAME=lox
      - FIRE_EVEN_NOT_CHANGED_SEC=600    # resend stalled values after specified seconds

